[buildPlans.bunni]
family = "bunni"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.bunni.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner"
f = "flat-hook"
g = "earless-corner"
i = "zshaped"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "zshaped"
m = "short-leg"
q = "earless-corner"
r = "corner-hooked"
t = "flat-hook"
u = "toothless-rounded"
w = "curly"
y = "straight-turn"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-alpha = "tailed-barred"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
lower-xi = "rounded"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-capital-u = "straight-turn"
one = "base"
four = "closed"
six = "closed-contour"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "closed-contour"
asterisk = "hex-low"
underscore = "low"
pilcrow = "low"
caret = "high"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
ampersand = "upper-open"
at = "short"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
question = "corner-flat-hooked"
punctuation-dot = "square"
diacritic-dot = "square"

[buildPlans.bunni.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "single-storey-earless-corner-serifed"
d = "toothed-serifless"
e = "flat-crossbar"
g = "single-storey-serifed"
i = "tailed-serifed"
l = "tailed-serifed"
u = "toothless-corner"
y = "cursive-flat-hook"
five = "oblique-upper-left-bar"
seven = "curly-serifed"

[buildPlans.bunni.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.bunnit]
family = "bunnit"
spacing = "term"
serifs = "sans"
no-cv-ss = true

[buildPlans.bunnit.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner"
f = "flat-hook"
g = "earless-corner"
i = "zshaped"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "zshaped"
m = "short-leg"
q = "earless-corner"
r = "corner-hooked"
t = "flat-hook"
u = "toothless-rounded"
w = "curly"
y = "straight-turn"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-alpha = "tailed-barred"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
lower-xi = "rounded"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-capital-u = "straight-turn"
one = "base"
four = "closed"
six = "closed-contour"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "closed-contour"
asterisk = "hex-low"
underscore = "low"
pilcrow = "low"
caret = "high"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
ampersand = "upper-open"
at = "short"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
question = "corner-flat-hooked"
punctuation-dot = "square"
diacritic-dot = "square"

[buildPlans.bunnit.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "single-storey-earless-corner-serifed"
d = "toothed-serifless"
e = "flat-crossbar"
g = "single-storey-serifed"
i = "tailed-serifed"
l = "tailed-serifed"
u = "toothless-corner"
y = "cursive-flat-hook"
five = "oblique-upper-left-bar"
seven = "curly-serifed"

[buildPlans.bunnit.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.bunniq]
family = "bunniq"
spacing = "quasi-proportional-extension-only"
serifs = "sans"
no-cv-ss = true

[buildPlans.bunniq.variants.design]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner"
f = "flat-hook"
g = "earless-corner"
i = "zshaped"
j = "flat-hook-serifed"
k = "symmetric-touching-serifless"
l = "zshaped"
m = "short-leg"
q = "earless-corner"
r = "corner-hooked"
t = "flat-hook"
u = "toothless-rounded"
w = "curly"
y = "straight-turn"
long-s = "flat-hook"
eszet = "longs-s-lig"
lower-alpha = "tailed-barred"
lower-delta = "flat-top"
lower-lambda = "straight-turn"
lower-xi = "rounded"
cyrl-capital-ka = "straight-serifless"
cyrl-ka = "straight-serifless"
cyrl-capital-u = "straight-turn"
one = "base"
four = "closed"
six = "closed-contour"
seven = "curly-serifless"
eight = "crossing-asymmetric"
nine = "closed-contour"
asterisk = "hex-low"
underscore = "low"
pilcrow = "low"
caret = "high"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "slanted"
ampersand = "upper-open"
at = "short"
dollar = "interrupted"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
lig-ltgteq = "slanted"
question = "corner-flat-hooked"
punctuation-dot = "square"
diacritic-dot = "square"

[buildPlans.bunniq.variants.italic]
capital-g = "toothless-rounded-serifless-hooked"
capital-k = "symmetric-touching-serifless"
a = "single-storey-earless-corner-serifed"
d = "toothed-serifless"
e = "flat-crossbar"
g = "single-storey-serifed"
i = "tailed-serifed"
l = "tailed-serifed"
u = "toothless-corner"
y = "cursive-flat-hook"
five = "oblique-upper-left-bar"
seven = "curly-serifed"

[buildPlans.bunniq.widths.normal]
shape = 600
menu = 5
css = "normal"
