[buildPlans.bunni]
family = "bunni"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.bunni.variants.design]
capital-a = "curly-serifless"
capital-b = "standard-serifless"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifed"
capital-p = "open"
capital-r = "straight-open"
capital-s = "unilateral-inward-serifed"
capital-u = "toothless-corner"
capital-v = "curly"
capital-w = "curly"
capital-y = "curly-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner"
c = "unilateral-inward-serifed"
d = "toothless-rounded-serifless"
e = "flat-crossbar"
f = "serifless"
g = "earless-corner"
h = "straight"
i = "zshaped"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "zshaped"
m = "top-left-serifed"
n = "straight"
p = "motion-serifed"
q = "earless-corner-tailed"
r = "serifless"
s = "unilateral-inward-serifed"
t = "flat-hook-short-neck"
u = "tailed"
v = "curly"
w = "straight-vertical-sides-motion-serifed"
x = "straight-serifless"
y = "curly"
one = "base"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "curly-serifless"
eight = "two-circles"
nine = "open-contour"
caret = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "upright"
ampersand = "et-toothless-rounded"
at = "short"
dollar = "through-cap"
cent = "through"
percent = "rings-segmented-slash"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.bunni.variants.italic]
capital-c = "bilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothed-serifless-hooked"
capital-h = "top-left-serifed"
capital-l = "motion-serifed"
capital-t = "motion-serifed"
capital-u = "motion-serifed"
capital-v = "curly-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "curly-motion-serifed"
a = "single-storey-tailed"
b = "toothless-corner-motion-serifed"
c = "bilateral-inward-serifed"
d = "toothless-rounded-serifed"
e = "rounded"
f = "diagonal-tailed"
g = "single-storey-serifless"
h = "straight-top-left-serifed"
i = "serifed-diagonal-tailed"
j = "flat-hook-serifed"
k = "diagonal-tailed-cursive-serifless"
l = "serifed-diagonal-tailed"
m = "top-left-serifed"
p = "motion-serifed"
q = "diagonal-tailed-motion-serifed"
s = "bilateral-inward-serifed"
t = "diagonal-tailed-short-neck"
u = "motion-serifed"
v = "cursive-serifed"
w = "cursive-motion-serifed"
x = "curly-serifless"
y = "cursive-flat-hook-motion-serifed"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "closed-non-crossing"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "curly-serifed"
eight = "two-circles"
nine = "straight-bar"
caret = "medium"
ampersand = "et-toothed"
dollar = "interrupted-cap"
cent = "bar-interrupted"
question = "corner-flat-hooked"

[buildPlans.bunnit]
family = "bunnit"
spacing = "term"
serifs = "sans"
no-cv-ss = true

[buildPlans.bunnit.variants.design]
capital-a = "curly-serifless"
capital-b = "standard-serifless"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifed"
capital-p = "open"
capital-r = "straight-open"
capital-s = "unilateral-inward-serifed"
capital-u = "toothless-corner"
capital-v = "curly"
capital-w = "curly"
capital-y = "curly-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner"
c = "unilateral-inward-serifed"
d = "toothless-rounded-serifless"
e = "flat-crossbar"
f = "serifless"
g = "earless-corner"
h = "straight"
i = "zshaped"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "zshaped"
m = "top-left-serifed"
n = "straight"
p = "motion-serifed"
q = "earless-corner-tailed"
r = "serifless"
s = "unilateral-inward-serifed"
t = "flat-hook-short-neck"
u = "tailed"
v = "curly"
w = "straight-vertical-sides-motion-serifed"
x = "straight-serifless"
y = "curly"
one = "base"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "curly-serifless"
eight = "two-circles"
nine = "open-contour"
caret = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "upright"
ampersand = "et-toothless-rounded"
at = "short"
dollar = "through-cap"
cent = "through"
percent = "rings-segmented-slash"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.bunnit.variants.italic]
capital-c = "bilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothed-serifless-hooked"
capital-h = "top-left-serifed"
capital-l = "motion-serifed"
capital-t = "motion-serifed"
capital-u = "motion-serifed"
capital-v = "curly-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "curly-motion-serifed"
a = "single-storey-tailed"
b = "toothless-corner-motion-serifed"
c = "bilateral-inward-serifed"
d = "toothless-rounded-serifed"
e = "rounded"
f = "diagonal-tailed"
g = "single-storey-serifless"
h = "straight-top-left-serifed"
i = "serifed-diagonal-tailed"
j = "flat-hook-serifed"
k = "diagonal-tailed-cursive-serifless"
l = "serifed-diagonal-tailed"
m = "top-left-serifed"
p = "motion-serifed"
q = "diagonal-tailed-motion-serifed"
s = "bilateral-inward-serifed"
t = "diagonal-tailed-short-neck"
u = "motion-serifed"
v = "cursive-serifed"
w = "cursive-motion-serifed"
x = "curly-serifless"
y = "cursive-flat-hook-motion-serifed"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "closed-non-crossing"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "curly-serifed"
eight = "two-circles"
nine = "straight-bar"
caret = "medium"
ampersand = "et-toothed"
dollar = "interrupted-cap"
cent = "bar-interrupted"
question = "corner-flat-hooked"

[buildPlans.bunniq]
family = "bunniq"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true

[buildPlans.bunniq.variants.design]
capital-a = "curly-serifless"
capital-b = "standard-serifless"
capital-c = "unilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-g = "toothless-corner-serifless-hooked"
capital-j = "serifed"
capital-p = "open"
capital-r = "straight-open"
capital-s = "unilateral-inward-serifed"
capital-u = "toothless-corner"
capital-v = "curly"
capital-w = "curly"
capital-y = "curly-serifless"
a = "single-storey-earless-corner-tailed"
b = "toothless-corner"
c = "unilateral-inward-serifed"
d = "toothless-rounded-serifless"
e = "flat-crossbar"
f = "serifless"
g = "earless-corner"
h = "straight"
i = "zshaped"
j = "flat-hook-serifed"
k = "curly-serifless"
l = "zshaped"
m = "top-left-serifed"
n = "straight"
p = "motion-serifed"
q = "earless-corner-tailed"
r = "serifless"
s = "unilateral-inward-serifed"
t = "flat-hook-short-neck"
u = "tailed"
v = "curly"
w = "straight-vertical-sides-motion-serifed"
x = "straight-serifless"
y = "curly"
one = "base"
four = "closed"
five = "oblique-upper-left-bar"
six = "open-contour"
seven = "curly-serifless"
eight = "two-circles"
nine = "open-contour"
caret = "low"
paren = "flat-arc"
brace = "curly-flat-boundary"
number-sign = "upright"
ampersand = "et-toothless-rounded"
at = "short"
dollar = "through-cap"
cent = "through"
percent = "rings-segmented-slash"
question = "smooth"
punctuation-dot = "round"
diacritic-dot = "round"

[buildPlans.bunniq.variants.italic]
capital-c = "bilateral-inward-serifed"
capital-d = "standard-unilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothed-serifless-hooked"
capital-h = "top-left-serifed"
capital-l = "motion-serifed"
capital-t = "motion-serifed"
capital-u = "motion-serifed"
capital-v = "curly-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "curly-motion-serifed"
a = "single-storey-tailed"
b = "toothless-corner-motion-serifed"
c = "bilateral-inward-serifed"
d = "toothless-rounded-serifed"
e = "rounded"
f = "diagonal-tailed"
g = "single-storey-serifless"
h = "straight-top-left-serifed"
i = "serifed-diagonal-tailed"
j = "flat-hook-serifed"
k = "diagonal-tailed-cursive-serifless"
l = "serifed-diagonal-tailed"
m = "top-left-serifed"
p = "motion-serifed"
q = "diagonal-tailed-motion-serifed"
s = "bilateral-inward-serifed"
t = "diagonal-tailed-short-neck"
u = "motion-serifed"
v = "cursive-serifed"
w = "cursive-motion-serifed"
x = "curly-serifless"
y = "cursive-flat-hook-motion-serifed"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "closed-non-crossing"
five = "vertical-upper-left-bar"
six = "straight-bar"
seven = "curly-serifed"
eight = "two-circles"
nine = "straight-bar"
caret = "medium"
ampersand = "et-toothed"
dollar = "interrupted-cap"
cent = "bar-interrupted"
question = "corner-flat-hooked"
