add_newline = false
format = "$status${custom.sudo}${custom.notsudo}[>](bold italic dimmed blue) [  ](blue)$directory$cmd_duration$character"
# bg:#5e5a76
right_format="${custom.gitbranch}$git_status"
# right_format = "${custom.sudo}[|](bold #524f67) $status$cmd_duration$username$time"
continuation_prompt = "[+](bold #c4a7e7) "
#  <-- folder icon
#  <-- git icon

[character]
success_symbol = "[▶](bright-purple)"
error_symbol = "[▶](bold red)"
# vicmd_symbol = "[](bold #c4a7e7)"
vicmd_symbol = "[▼](bold purple)"

[time]
disabled = true
format = "[$time]($style)"
style = "bold bright-blue"

[status]
disabled = false
format = "[\\(](bold #524f67)[$status]($style)[\\)](bold #524f67)"
style = "bold italic bright-red"

[cmd_duration]
disabled = false
format = "[{](bold #524f67)[$duration]($style)[}](bold #524f67)"
show_milliseconds = false
style = "bold italic #ebbcba"
min_time = 5000

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = ""
truncate_to_repo = false
style = "dimmed blue"
# bg:#5e5a76
repo_root_style = "bold italic #6e6a86"
# bg:#3e3a56
read_only_style = "bold bright-red"
fish_style_pwd_dir_length = 1
truncation_length = 2

[username]
format = "[$user]($style)[@](bold #524f67)"
show_always = true
style_root = "bold bright-red"
style_user = "dimmed blue"

[git_status]
format = "([{[$all_status$ahead_behind](bold italic #6e6a86)}]($style))[\\)](bold #524f67)"
# bg:#3e3a56
modified = "M"
renamed = "R"
conflicted = "≠"
deleted = ""
staged = "+"
untracked = "?"
style = 'bold #6e6a86'
# bg:#3e3a56

[custom.sudo]
command = "echo '!'"
when = "sudo -vn &>/dev/null && [ \"$(whoami)\" != \"root\" ]"
description = "prints a ! if you have sudo creds, otherwise nothing"
shell = ["bash", "--norc", "--noprofile"]
style = "bold italic dimmed red"
format = "[$output]($style)"

[custom.gitbranch]
command = "echo -n \"$(git branch --show-current)\""
when = "git rev-parse --is-inside-work-tree &>/dev/null"
description = "shows git branch if you are in a git repo"
shell = ["bash", "--norc", "--noprofile"]
style = "bold italic #6e6a86"
# (branch in folder) format = " [$output](bold $style)[ in ]($style)"
format = "[\\(](bold #524f67)[$output]($style)"

[custom.notsudo]
command = "echo '>'"
when = "! sudo -vn &>/dev/null || [ \"$(whoami)\" = \"root\" ]"
shell = ["bash", "--norc", "--noprofile"]
style = "bold italic dimmed red"
format = "[$output]($style)"
